repos:
  - repo: https://github.com/PyCQA/autoflake.git
    rev: v2.2.1
    hooks:
      - id: autoflake
        language_version: python3.12

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python3.12

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.12 